
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/rnfastimage/EventEmitters.h>
#include <react/renderer/components/rnfastimage/Props.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>

namespace facebook {
namespace react {

extern const char FastImageViewComponentName[];

/*
 * `ShadowNode` for <FastImageView> component.
 */
using FastImageViewShadowNode = ConcreteViewShadowNode<
    FastImageViewComponentName,
    FastImageViewProps,
FastImageViewEventEmitter>;

} // namespace react
} // namespace facebook
